### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by lukewestby** [raisemarketplace/redux-loop#18]
#### Meta-issue to track future plans

- [x] Add `lift` effect
  - #16
- [x] Return an array from `loop` instead of an object for easy destructuring
  - #27
- [ ] Port redux examples
- [ ] Better test coverage
- [ ] Write full-length tutorial
